---
- name: Configure OpsVision Server
  hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: verify connection
      ansible.builtin.ping:
    
    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - git
          - docker
          - nginx
          - wget
        state: present
    
    - name: Start and enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
        
    - name: Add ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes
    
